### PR TITLE
API Rewrites

### PR DESCRIPTION
**Pull request by SquidDev**
To be merged after #27.

### CODE REVIEW

**Comment by SquidDev** [comment]
#28 is now fixed as of 5d28a09 and 7d7aab9.

@ElvishJerricco: Is the interface for visiting networks OK?

**Comment by ElvishJerricco** [comment]
Yea looks good.

**Comment by SquidDev** [comment]
Everything seems to work with this merged. Shall I push?

**Comment by ElvishJerricco** [comment]
Sure, if it works

**Pull request merged**
