### PR TITLE
Bridge peripheral & Modem block

### PR DESCRIPTION
**Pull request by SquidDev**
Implements #15

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
The bridge doesn't seem to call attach() on peripherals. It seems the issue about adding API for peripheral attachment handling might be important to add for this.

**Comment by SquidDev** [comment]
Hmmm, it should be called [here](https://github.com/SquidDev-CC/CC-Tweaks/blob/master/src/main/java/org/squiddev/cctweaks/core/network/modem/BasicModem.java#L117). I'll test this now. :confused:

**Comment by ElvishJerricco** [comment]
Would it be too crazy to try to isolate all calls to IPeripheral.attach() (including those in vanilla CC), and replace them with a different call to the theoretical PeripheralAttachmentRegistry proposed [here](https://github.com/SquidDev-CC/CC-Tweaks/issues/17)? It would delegate to the registered handlers, one of which simply calls IPeripheral.attach()

**Comment by SquidDev** [comment]
Well, we've got a core mod, so it is feasible. #17 is next on my to do list, though I'm probably going to have to rewrite the entire API so we are shipping interfaces and not code as much as possible. Something [like this](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv2/src/api/java/appeng/api/AEApi.java)

**Comment by ElvishJerricco** [comment]
That's a good idea. For now, I'll branch and see how much I can do with the peripheral attachment registry idea.

**Comment by SquidDev** [comment]
Thanks, I'm still confused about #16, so if you could also do something with that, it would be great.

**Comment by SquidDev** [comment]
I've implemented a turtle upgrade for the wireless bridge using the methods `bindToCard` and `bindFromCard`. Currently it also wraps the turtle as a peripheral so you can remotely turn it on and off. I wish that we could wrap turtles as OpenPeripheral's IInventory peripheral instead, but no such luck.

**Comment by SquidDev** [comment]
Progress!

**Comment by SquidDev** [comment]
I'm not sure about having it as a peripheral now. I might revert support for it from the original bridge as well as otherwise behaviour is inconsistent. The issue lies in the fact that nodes must occupy the middle slot of a multipart and this doesn't. I'll have to think about this.

I'm going to merge anyway, and maybe add this as another issue.

**Pull request merged**
