### PR TITLE
[WIP] LuaString binary support

### PR DESCRIPTION
**Pull request by SquidDev**
This is a semi-broken patch for the LuaJ string class. Events work but File IO and HTTP doesn't.

### CODE REVIEW

**Comment by SquidDev** [comment]
@ElvishJerricco

This is broken for HTTP because the HTTP API reads using readLine() ([See here](https://github.com/SquidDev-CC/Studio/blob/master/src/main/java/org/squiddev/ccstudio/computer/api/HttpAPI.java#L111-L116)).

Any ideas on how to fix it?

I'm testing using this script:
```lua
local function format(str)
	if type(str) ~= "string" then return tostring(str) end

	local result = ""
	for i = 1, #str, 1 do
		local char = str:sub(i, i)
		local b = string.byte(char)
		if b < 32 or b > 126 then
			char = "\\" .. b .. ""
		end
		result = result .. char
	end

	return result
end

local tests = {
	file = function(str)
        local a = fs.open("file", "w")
        a.write(str)
        a.close()


        a = fs.open("file", "r")
        local read = a.readAll()
        a.close()

        return read
	end,

	queue = function(str)
		os.queueEvent("ignore", str)
		local _, text = os.pullEvent("ignore")
		return text
	end
}

local function doTests(str)
	print("Tests with " .. format(str))
	for name, func in pairs(tests) do
		local result = func(str)
		 if result ~= str then
		    printError("No match " .. name)
		    print("  Expected " .. format(str))
		    print("  Got " .. format(result))
		 end
	end
end

doTests("abc\223\234")

do
	local result = http.get("https://raw.githubusercontent.com/SquidDev-CC/CC-Images/master/data/CC-Large.bmp")
	if not result then printError("Cannot read " .. result) end

	local contents = result.readAll()
	local a = fs.open("Download.bmp", "w")
	a.write(contents)
	result.close()
	a.close()

	a = fs.open("CC.bmp", "r")
	local other = a.readAll()
	a.close()

	if contents ~= other then
		printError("No match")
	end
end
```

**Comment by ElvishJerricco** [comment]
I'm guessing it's broken because of [this line in particular](https://github.com/SquidDev-CC/Studio/blob/master/src/main/java/org/squiddev/ccstudio/computer/api/HttpAPI.java#L115)? That one seems to add new lines at the end of every response no matter what. If this is the issue at hand, I think the solution would be to either change the HTTP API to preserve the original new lines (which it ought to do anyway for the sake of the weird Windows new line characters) and not append them manually. But also, we could just add a feature to HTTP, where from Lua you can specify that you want a binary handle, which would be nice anyway.

**Comment by ElvishJerricco** [comment]
There's also an issue with the [implementation](https://github.com/SquidDev-CC/CC-Tweaks/blob/92f68ed7c09fa338a319640c50c904a6bd044ea5/src/main/java/org/luaj/vm2/LuaString.java#L756-L796). One char does not equal one byte and vice versa. That will corrupt binary files. One char actually equals between one and four bytes. This is why LuaJ has its broken solution. It uses a method that mark which bytes construct a UTF8 value. Without it, there's no way to accurately reconstruct the original string using decodeAsUtf8, as a byte that was originally part of a UTF8 string could have been in any of the three left most bytes in the char.

So now that I think more about it, I don't think it's possible to fix the bug outright. I think it's probably better just to add a binary mode to the HTTP get and post methods.

**Comment by ElvishJerricco** [comment]
Of course I could be wrong, and there might be an actually good way to do the original plan.

**Comment by SquidDev** [comment]
I would have replied earlier but my computer thought that crashing everything would be the way to go :angry:.

I don't think we need to support UTF8 but the readline issue is undoubtedly what is causing the problem. Why CC doesn't implement files like normal OutputStreams I don't know *sigh*.

I think it should be possible to fix the bug, though I'm not sure if it can be done with pure ASM injection or if it should be a Dan thing to implement.

Would `String.getBytes()` work with UTF8?

**Comment by ElvishJerricco** [comment]
I was just about to say that. I guess it would probably work to use String.getBytes and String(byte[]) to construct and destruct Strings correctly.

**Comment by SquidDev** [comment]
I guess I could fix the buffer class [here](https://github.com/SquidDev-CC/Cobalt/blob/edf868b30bd8e0c0a214ceb5f2351d6402e44138/src/main/java/org/luaj/vm2/Buffer.java#L194-L199) and fix add custom methods to the string class for conversion.

That would fix the LuaJ classes, but we can't avoid that CC's own handling is broken.

**Comment by ElvishJerricco** [comment]
Yea I guess this could just turn out to be a mess of code that needs fixing because LuaJ is dumb. =/

**Comment by SquidDev** [comment]
I've started rewriting bits for the fun of it but I haven't made much progress. I'll see if I can patch the buffer class now as well and see what that does.

**Comment by SquidDev** [comment]
Right. It turns out that using `.getBytes()` is even more broken then using `.getChars()`. I think patching the HTTP class for binary transfers may be the better bet, however I'm not sure how do do that without infringing copyright.

**Comment by ElvishJerricco** [comment]
Wait how is getBytes even more broken?

**Comment by SquidDev** [comment]
`abc\223\234` produces `abc\239\191\189\239\191\189`. HTTP produces the same result which is even stranger. Looking at the `.getBytes()` it still converts using `StringCoding.encode` so that is to be expected.

**Comment by SquidDev** [comment]
I just don't think this is possible to fix :unamused:.

**Pull request closed without merging**
