### PR TITLE
Network Rewrite

### LINKED ISSUE #30: Network construction happens on tick updates
Modems don't ```findPeripherals()``` until tick updates are called on the tile entities. This leads to a couple of things:

1. When the network is invalidated, it takes a whole tick for peripherals to get found. This can bug out a program on a computer if it tries to access a peripheral during that tick.
2. The code is a mess. Lots of things have to happen in really strange places to make this work. For example, I'm going to have to implement peripherals detaching from networks when they're broken (when attached via modem) by writing something into ```onNeighborChanged```, which is *not* where that ought to be.

We should take a look at fixing this after we merge #29

### LINKED ISSUE #35: `attachToNetwork` not fired on world join
`attachToNetwork` is only called when placed or `peripheralEnabled` is toggled for modems blocks and `PartModem`. 

It should also be called on initial construction, otherwise peripherals never receive a network object. The easiest way would be to call `attachConnectedPeripherals()` after creating the modem. I feel this should probably be done within the TileEntities (`onWorldJoin` and `setWorldObj`) rather than within the base modem class.

I haven't tested but I imagine the same applies to `TileCable` and computers.

@ElvishJerricco: This is a trivial fix, I just want to check with you before applying it.

### PR DESCRIPTION
**Pull request by ElvishJerricco**
Closes #30

- [x] Re-implement several interfaces on several classes.
    - [x] On cable parts.
    - [x] On modem parts.
    - [x] On intermediate parts.
    - [x] On wireless bridges.
    - [ ] Wireless bridges for turtles
    - [x] On modem blocks.
    - [x] On vanilla cables.
- [x] Remove a ton of functionality that is now implemented more simply in `NetworkController`
- [x] Make `BasicModem` implement `INetworkedPeripheral` calls.
- [x] Instantiate a network when a node is placed down.
- [x] Wireless bridge bindings should provide nodes, not positions of nodes.
- [x] Remove `INetworkController` argument from `INetworkNode.receivePacket`

Additional features we should add at some point (added by @SquidDev).
 - [ ] Replace set of connections with a more efficient data structure. Ideally we should be able to find connections to/from any node without having to iterate through the list. A `Map<INetworkNode, Set<INetworkNode>>` would work, but it does mean a two way mapping is harder to ensure.
 - [ ] Bring back the unit tests. I deleted them in 3bc51af1a10666891fe4d72177e37fa15e373ca0 but it might be worth bringing them back in a different form to ensure that everything works correctly.
 - [ ] Optimise the network code. Currently removing a node recreates the entire network. This could be happening several hundred times on a chunk unload.
 - [ ] Cables cache connections
 - [ ] Send packets directly rather than on the update tick.

Fixes #35 and closes #30.

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Finally starting to make some headway on the code for this. Not compiling currently (changing the methods in INetworkNode, and still need to implement all the changes). But I think I've got a good plan for network changes.

First of all, the NetworkController class won't at all care about world positions and the like. Only INetworkNodes. So INetworkNode implementations have to implement `getConnectedNodes()`, which nicely removes the need for `getExtraNodes()`. Difference is that a cable now has to explicitly state that it connects to which cables on its sides. Network helper functions can make this easy.

Second, network modification. There are four modes of network modification I can think of.

* Disconnect
    * Ex: Put a cover between cables.
    * Call the network controller with `INetworkController.breakConnection(INetworkNode node1, INetworkNode node2)`.
    * Network controller starts with node1, scans the network to gather the new network.
        * During this scan, if `node2` is found, cut immediately.
        * This means the network didn't end up changed and no work needs doing.
    * Find any nodes in the old network no longer in the new network.
    * Remove these nodes from the network.
    * Create a new network starting at `node2` and allow it to populate itself.
* Connect
    * Ex: Remove a cover.
    * Call the network controller with `INetworkController.formConnection(INetworkNode existingNode, INetworkNode newNode)`.
    * If `newNode` is already on the network, no work needs doing. Cut.
    * Add `newNode` to the network and start a scan at `newNode`.
        * Assimilate nodes by removing them from their old network and adding them to this one.
* Node removed
    * Ex: Break a cable block.
    * Call the network controller with `INetworkController.removeNode(INetworkNode node)`.
    * Use `node.getConnectedNodes()` to find nodes not destroyed.
    * If there is only one, cut. No network change.
    * Perform a network scan for each one of these nodes to form all the newly severed networks.
        * After scanning one network, remove any nodes already found in a network from the list of nodes to start scanning from.
    * If there's only one found network, no network change has been made.
    * Otherwise, create new network controllers for each of the new networks.
* Node added
    * Ex: Place a cable block.
    * Call the network controller with `INetworkController.addNode(INetworkNode node)`.
    * Add the node to the network, and start a network scan at that node.
        * Should be similar to `formConnection()`.

There's one really interesting consequence of this. Let me preface with: I don't think we should plan to implement this next idea any time soon.

We don't have to treat cables as a grid of nodes. We can actually just treat a segment of cables that doesn't branch at all as one node basically. Just kinda interesting. Potential future optimization.

Anyway, after any of these operations, check the old list of peripherals against the new list of peripherals. Based on any changes found, inform modems, peripherals, etc. This does mean that any networks spawned as a result of these operations will have to be aware of the list of peripherals they used to have before severing.

**Comment by SquidDev** [comment]
Sounds good. My one issue with `getConnectedNodes` is that every node has to scan the world six times to find them. This shouldn't be a problem it just seems slightly annoying. How will disconnect work between two multipart cables though - both cables have to be notified that a cover has been removed and so update their `getConnectedNodes` list, maybe I'm just misunderstanding.

We'll also have to take care that a provider may return a node that represents the same position but is a different object (if someone wanted to have redstone blocks as nodes they would return a new node instance every time we request it). This could slow down searching slightly as I guess we will have to check equality linearly rather than using a `HashMap/HashSet/etc...` as we can't rely on `getHashCode`. There might be a way to get around it but I don't know.

Another thing to remember is that we have to store distance from one node to another (for network packets) so we will still have to have methods to traverse the network normally.

**Comment by ElvishJerricco** [comment]
It will be slightly annoying to have to search all six sides in the getConnectedNodes thing, but I think that can be mitigated by a simple helper function.

Disconnect between two multipart cables is just an ordinary disconnect. If I put a cover inside one multipart to disconnect from the other, one will call `breakConnection`. At this point, the cables simply employ their own logic to stop rendering towards each other. We might want a subclass of `INetworkNode` like `IWorldNetworkNode`, whose purpose is to be a network node that indicates if cables should render toward them in a direction. Node providers would return these instead I guess.

Providers that are providing a new instance of INetworkNode for every time we request a node would be wrongly implemented if they didn't override `equals

**Comment by ElvishJerricco** [comment]
Apologies for the slow progress. I've had a busy week. But I'm definitely getting somewhere with this. Not going to push until all the INetworkNode changes are implemented across the board (don't want to push code that doesn't compile). But there's an interesting difficulty.

Should networks remember which nodes attach which nodes? Or should they just repeatedly use `getConnectedNodes` to figure out which nodes connect which?

I think I should put the effort into making it remember which nodes connect which, because this way nodes like the modem block don't have to be able to tell the network that they connect to adjacent cables. Instead, we just have to know that the cable said it connects to the modem block. Keeps strange code out of the modem block node.

Also, I think I have a good way to do the packet transmitting. In `INetworkNode`, there will be `getDistanceToNode(node)`, which will return the distance between the node and the parameter. It will be guaranteed to only be called by passing a node that could be gotten from `getConnectedNodes`, so that the node can return a value that it can easily determine (for cable blocks, it'll be 1 to adjacent cables, and 0 to multipart nodes in the block space for example). This means wireless bridges will still be able to accurately represent distance.

**Comment by SquidDev** [comment]
Don't worry about slow progress, I'm so thankful of all the work you are doing on this. If there is anything I can help with I'm happy to.

Hmmmm, I really don't know. Ideally `INetworkNode` would be as easy to implement as possible, but also we need to cope with annoying things such as the distance between nodes. I just don't see a better way though. Uggghr.

**Comment by ElvishJerricco** [comment]
It sure would be nice if the norm in MC modding was Scala. Traits would be sweet.

**Comment by SquidDev** [comment]
I seem to remember [this](https://github.com/SpongePowered/Mixin) might make its way into ForgeGradle at some point. Its effectively mixins for Java. [The wiki](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Understanding-Mixin-Architecture) describes it better.

**Comment by ElvishJerricco** [comment]
Interesting. Although honestly, that just seems like a less capable (albeit, more streamlined) version of the transformation library in CC-Tweaks. And I don't see a way to use it to implement essentially default methods for interfaces. Although actually, I believe Mojang said they plan on shipping a JVM with MC, guaranteeing a certain java version. When they get there, we can start using Java 8 features.

**Comment by SquidDev** [comment]
Well, we could add Mixins to CCTweaks :stuck_out_tongue:. They are packaging Java 8 with Windows/Mac launchers, but not with FTP/Curse/Tekkit/etc... launchers. [60% use Java 8](https://twitter.com/Dinnerbone/status/592967371226226688) but that really isn't enough, maybe another year :cry: .

**Comment by ElvishJerricco** [comment]
Ugh. One of these days I'll write a Lambda and mean it... =P

**Comment by SquidDev** [comment]
I really don't like Java's lambdas. I'm so used to .Net's LINQ which is so much better and more flexible. But anyway, enough of Java rants...

**Comment by ElvishJerricco** [comment]
Yea back to the matter at hand,

I'm writing a utility class to help track connections. Basically, UnorderedPair<X, Y> is a class that has two final instance variables. Its `equals` and `hashCode` methods are overridden so that `new UnorderedPair<Integer, String>(1, "hey").equals(new UnorderedPair<String, Integer>("hey", 1)) == true`. Idea being the network controller can have a `HashSet<UnorderedPair<INetworkNode, INeworkNode>>` of pairs representing connections made.

**Comment by ElvishJerricco** [comment]
I think the biggest issue at hand is determining to add a new network to the world. When a cable is placed down, we want it so that the networks that the node might become a part of reach out to it and add it, instead of the node reaching out and adding itself. This way the node doesn't have to know every possible way it might be connected to a network. For example, someone might add a node that connects to distant nodes that don't even know they're being connected to this way. In this case, it's up to that strange kind of node to add the distant node, instead of being up to the distant node. So when the distant node is added to the world, it can't know which networks it'll be a part of.

Point is, if a node doesn't know what networks it'll be a part of, when does it know to create its own network for itself?

**Comment by SquidDev** [comment]
So a similar problem would be covers. If you put the connection code inside the placed node, it needs to check if the other node can accept connections on that face, and if the neighbour handles it then it needs to check if the placed node can accept connections. Neither way is nice.

I'm going to have to go and think about this....

**Comment by ElvishJerricco** [comment]
Well covers are pretty simple. The cable being covered knows what's on that side and can the do the appropriate `breakConnection` call. Or at the very least, when `onNeighborChanged` is called, it can find out what it can't connect to anymore and call `breakConnection` for that as well.

Perhaps nodes should create a network that just contains that node when they're added. Then any networks that want that node can assimilate that network. And if that doesn't happen, it has the network it needs.

**Comment by ElvishJerricco** [comment]
In fact, because I'm changing to tracking connections in the network controller, `getConnectedNodes` isn't even necessary. Instead, nodes will simply be added by something, instead of the network reaching out to find them.

**Comment by ElvishJerricco** [comment]
Anyway I think the only nodes that will actually need to create a network are modems. The only time a network's services are needed are when a modem is active. So we can go from there I think.

**Comment by ElvishJerricco** [comment]
Also, why does all our code use `distanceTravelled` variables as integers? Shouldn't they be doubles?

**Comment by SquidDev** [comment]
Were they not originally integers? I think the original network visitor code used integers. Doubles only makes sense when you need to travel diagonally - so for wireless networks but for a wired network you can only travel a whole block so an integer seems to make more sense.

**Comment by ElvishJerricco** [comment]
But with the concept of the network API, we have no reason to assume that we will only travel in non-diagonal lines. Wireless bridges, for example, should add a transmission distance that has to be a double.

**Comment by SquidDev** [comment]
Hmmm, hadn't thought about that... I guess we can no longer consider them exclusively as 'wired' networks and yeah, a double is fine.

**Comment by ElvishJerricco** [comment]
Alright. I'm at a point of API-level stability I think. Do you want me to push my changes? Here's what's left:

- [ ] Re-implement several interfaces on several classes.
- [ ] Remove a ton of functionality that is now implemented more simply in `NetworkController`
- [ ] Make the network controller implement the `INetworkedPeripheral` calls, so modems don't have to.

The volume of each of these things is pretty huge, but since I'm at a point where the API isn't changing, I think we can work together on the remainder of this.

**Comment by ElvishJerricco** [comment]
Also worth noting that it totally doesn't compile yet, because of the need to re-implement so many interfaces.

**Comment by SquidDev** [comment]
Go for it!

**Comment by SquidDev** [comment]
Sorry, only just got round to pulling. Is it safe to remove the `INetworkNode.lock()` method? Presumably we can now lock on the entire network rather than each node's lock object.

Just wondering why `receivePacket` takes a `INetworkController` object, will that not be identical to `getAttachedNetwork`? 

Could `networkInvalidated` take two maps - added and removed peripheral maps instead of a map of old peripherals? I say this because the list of old peripherals is only useful if you need to compare it with the new one.

Thoughts?

**Comment by ElvishJerricco** [comment]
I believe it would be safe to remove the `lock` method.

You're right, `receivePacket` probably doesn't need the `INetworkController` argument. My mistake.

`networkInvalidated` passes the old list in just because it's easier to calculate, but perhaps that would be better.

**Comment by ElvishJerricco** [comment]
BTW, I'm working on BasicModem right now, so I've got that one covered.

**Comment by SquidDev** [comment]
I'm having a look at doing `TileCable`, though I can't guarantee anything. On the case of `attachToNetwork`, should I throw an exception if I already have a network, fail silently or succeed?

**Comment by ElvishJerricco** [comment]
Well theoretically, the NetworkController class should never ever call `attachToNetwork` without first calling `detachFromNetwork`, except sometimes when `getAttachedNetwork` returns null. What do you think should be the policy on this?

**Comment by ElvishJerricco** [comment]
Also, `TileCable` would be so much better / easier if it used `BasicModem`.

**Comment by SquidDev** [comment]
I'm think fail fast and hard is better, if we are trying to attach twice then something has gone wrong somewhere and we need to know about it as soon as possible.

I guess. I'm stuck between 'change all the things' and backwards compatibility. Looking at `TileCable` that will probably be the hardest to do as it does pretty much everything - connections, modems, etc...

**Comment by SquidDev** [comment]
Also, wondering if `INetworkAccess` should use the same method names as `INetworkController`, though obviously we can't inherit from it?

**Comment by ElvishJerricco** [comment]
That's not a bad idea. But ultimately I don't think it's super important.

I've got `BasicModem` migrated. I'll move onto it's subclasses if you want to tackle making `INetworkedPeripheral` and `INetworkAccess` work.

**Comment by ElvishJerricco** [comment]
Modems proved to be surprisingly simple. Just need to update nodes I guess.

**Comment by ElvishJerricco** [comment]
I don't think we want the `BasicModem` implementing INetworkAccess. The network controller has to be able to call `attachToNetwork` and `detachFromNetwork` with the access object, which it has no way to know is the modem. I think it'd be better if the network controller performed all of the `INetworkedPeripheral` operations and provided its own access objects.

**Comment by SquidDev** [comment]
The one issue is that the network controller needs to know where a packet is transmitted from `transmitPacket(INetworkNode, Packet)` so we need a custom `INetworkAccess` that knows what node it is. I guess we can have a simple `NodeNetworkAccess` which holds a node and a controller, but then `BasicModem` would need to store an instance of that instead. Thoughts?

**Comment by ElvishJerricco** [comment]
My thought was that `NetworkController` would have a `Map<String, NodeNetworkAccess> attachedNetworkedNodes` map instance variable. In the packet sending code, whenever it gets to a node, it checks if the node has any networked peripherals and sends the remembered `NodeNetworkAccess`

**Comment by ElvishJerricco** [comment]
To expand on why I think the `INetworkAccess` should be handled by the controller: This way, `INetworkNode`s don't have to implement any `INetworkAccess` stuff for peripherals they attach. The network handles that for them, which is nice, because it removes unnecessary boiler plate and implementation from the nodes.

**Comment by SquidDev** [comment]
Sorry, I'm in the middle of exam season so just haven't had a proper chance to look at things yet. 

I'm probably being really dumb but for `Map<String, NodeNetworkAccess>`, what would the `String` key be? I guess the peripheral name, but then we might have multiple `INetworkAccess` instances for one node.

**Comment by ElvishJerricco** [comment]
Yea it'd be the peripheral name. Perhaps they key would be better as the node that provided the peripheral?

**Comment by ElvishJerricco** [comment]
I gave it a look to see if I could do it easily before pushing all my changes over the last day, and it's a little weird. It'd definitely just be easier if the modem took care of it, i think.

So yea, I guess we'll just have the modem handle networked peripherals.

**Comment by ElvishJerricco** [comment]
Issue is that it's not always the attached network controller that calls `detachFromNetwork`, so it won't always be sane where the `INetworkedPeripheral` calls go if they're in `NetworkController`. Just means it's easier to put them in the appropriate modem methods. (Although, this is another instance where Java 8 default interface methods would be great. We could implement methods in the INetworkNode interface to do this job on its own).

**Comment by ElvishJerricco** [comment]
Does FMP not provide a way to see when a part is added to the tile? I know there's `onPartChanged`, but that's called in more circumstances than just when a part is added, and it doesn't make any distinction. How do we determine when a part is added? We need to be able to respond to this so that `CablePart` can add that part to the network if its a node.

**Comment by SquidDev** [comment]
No, don't think so. You can listen for remove checking if the `TMultiPart` parameter of `onPartChanged`  is still in the multipart.

**Comment by ElvishJerricco** [comment]
Well the solution I used was just adding connections between the cable and every part in the tile. The network properly handles trying to add an already existing connection, so it's fine.

**Comment by ElvishJerricco** [comment]
INetworkedPeripherals! We're definitely getting somewhere here.

**Comment by ElvishJerricco** [comment]
Wireless bridges! Got the bindings reworked. Am I incorrect to handle connection forming / breaking in the `NetworkBindings` class?

**Comment by ElvishJerricco** [comment]
As for `TileCable`s, I think we have an opportunity to abstract cable logic a bit here. Instead of making `TileCable` an `IWorldNetworkNode`, we can make it an `IWorldNetworkNodeHost`, doing the same to `PartCable`. The node they provide is something similar to `BasicModem`, but for cables instead of modems. It'll handle the logic for connections and forming / breaking them. And `TileCable` can just keep an instance of `SinglePeripheralModem`. And it calls `formConnection` on the network controller to put that modem on the network.

**Comment by SquidDev** [comment]
Gosh you've been busy! The `NetworksBindings` looks good. :+1: 

I had a look at abstracting some code out in #32 but I thought that at the time there was no point. Now nodes are doing much more work I think we should abstract away as much as code as possible.

I have a wee bit more time now if there is anything left to work on?

**Comment by SquidDev** [comment]
Not relevant at all, but there have been [137 commits, 10,000 additions and 6,000 deletions](https://github.com/SquidDev-CC/CC-Tweaks/compare/v1.7.10-0.1.4.2...master) since the last release. Wow.

**Comment by ElvishJerricco** [comment]
If you want to work on what I just talked about with `TileCable`, that'll make re-implementing the intermediate part a hundred times easier (it'll basically be a copy of `TileCable` =P).

I'll go ahead and look into making nodes instantiate their networks when they're added, then we're basically done!

And wow. That's awesome. The `files changed` tab is so long lol.

**Comment by SquidDev** [comment]
Ta.

I'm in a sticky situation... I've got pretty much everything working (well, I guess I have). However we should only scan for peripherals if the modem is a `WiredModemWithCable`. However this can obviously change and we should account for that.

As far as I can see we currently offer no way of updating the block's ability to connect to peripherals. I've thought about overriding `isPeripheralEnabled` but `updateEnabled` will not continue. I don't want to add an additional `canPeripheralConnect` method or something. The alternative would be to replace `isPeripheralEnabled` calls with `peripheralEnabled` fields in `updateEnabled` but that seems hacky.

**Comment by SquidDev** [comment]
This won't work as placing a modem shouldn't connect but placing a cable afterwards should. :tired_face:

**Comment by ElvishJerricco** [comment]
I guess I missed that `isEnabled` existed. My bad.

`INetworkController.invalidateNetwork()` will clear the peripheral list and have it re-search its nodes for attached peripherals. That is the whole purpose of that method now.

Anyway I think we should be implementing it so that we have a `BasicCable` class (no pun intended), analogous to `BasicModem`, but for cables. `TileCable`s (and `PartCable`s) should become `IWorldNetworkNodeHost`s, instead of nodes themselves, providing its `BasicCable` instance. Then it should have a `BasicModem` instance if it has a modem, and it should call `INetworkController.formConnection(cable, modem)` to attach that modem to the network. Should keep the code cleanest and most modular.

**Comment by ElvishJerricco** [comment]
I've been so busy lately... But here's what I've managed to put together. Plan is to implement `SingleModemCable` on `TileCable` and the intermediate part. Although it is possible that the intermediate part needs to do something different so it can connect to the other multipart nodes in the block.

Also, `writeDesc` and `readDesc` should probably be used to sync the connection map, so the client doesn't have to do anything to track a network. Which means writing more `world.isRemote` guards.

**Comment by SquidDev** [comment]
You Sir are a marvel. I have been both busy and distracted by [this](http://www.computercraft.info/forums2/index.php?/topic/23439-tua-feedback-on-syntax/) and so forgot to work on this. Sorry :sob:.

I initially had it syncing the connection map when I implemented caching. However the issue was that even on my dev machine the slight network lag meant that you would place the cable and a couple of ticks later the connection would appear between them. Clients shouldn't hold a network (obviously) but I feel they should be able to check if connections can appear - connection syncing seems to be too vulnerable to de-syncing issues.

**Comment by ElvishJerricco** [comment]
Well syncing is just the simplest way and I can't imagine any major issues resulting.

Also Tua looks cool. I'll take a look at it tonight.

**Comment by ElvishJerricco** [comment]
I think that does `TileCable`.

Why does the intermediate part have to be such a derp? =/ I'm not sure the best way to go about implementing that...

**Comment by ElvishJerricco** [comment]
Getting much closer to this... But how do we initialize an initial network? Right now, it would work best if every node instantiated a network of its own to use until it gets assimilated or something. But that's a bit painful, and we'd have to expose `NetworkHelpers` as public API so that people could instantiate a network controller.

Any ideas?

**Comment by SquidDev** [comment]
A couple of options:
- Use Forge hooks to listen to TE creation/block placing. Then, if this is a node we can create a network. This has the advantage that only one place has to deal with network creation/assimilation but doesn't seem a great solution.
- Public API with something like `connectNetwork(IWorldNetworkNode)` which creates a network or joins a current one.
Or something in your suggestions. I don't really think any are perfect though.

**Comment by ElvishJerricco** [comment]
I'm really stumped on this problem... I *think* we should just use Forge hooks to listen for tile entity creation. Do you disagree?

**Comment by SquidDev** [comment]
To be honest, I'm still slightly scared of this. :worried:. I do think hooks are probably the most 'forgy' way to go. I can't think of a scenario where people would need to write custom joining code so I'm all for it.

**Comment by ElvishJerricco** [comment]
Maybe we can just have cables instantiate their network. Then they craw to absorb the whole network?

**Comment by SquidDev** [comment]
That would work, though if there is a situation where they want to write custom cables it would break. Hmmm.

**Comment by ElvishJerricco** [comment]
Then perhaps we'll have API for creating network objects, but no one will use it unless they're making their own cables

**Comment by SquidDev** [comment]
Sounds like a plan...

**Comment by ElvishJerricco** [comment]
I really want this feature done =P CCTransport is begging to use the network.

**Comment by SquidDev** [comment]
Yeah, I've got a bit more free time so I might be able to spend some decent time programming on this.

**Comment by SquidDev** [comment]
Right API method it is, though I think most, if not all nodes should call it - not just cables. For instance you can chain modem blocks together to create a network without cables.

**Comment by SquidDev** [comment]
I'm guessing we don't need to fire a network invalidation call when placing the node?

**Comment by ElvishJerricco** [comment]
Yea that'd go with the binding code.

**Comment by SquidDev** [comment]
Right, everything builds but there are a ton of NPEs on world load. I think it is because we are doing so much before we've had the `worldObj` set.

**Comment by ElvishJerricco** [comment]
So satisfying to see the build passing...

But yea I'm sure we've got a lot of logical issues ahead. But that should (hopefully) be a nice and swift set of fixes. I'll be able to look at these issues quite a bit later tonight (busy day). But I'm excited to actually start experimenting in the world with these

**Comment by SquidDev** [comment]
I've tried to fix the `setState` bug, but they all boil down to saving the state until we receive the world instance. This seems kinda ugly and we have to repeat it for every modem TE.

**Comment by ElvishJerricco** [comment]
Well as for creating the network, cables are already coded to assimilate nodes that get placed. So nodes just need to create a network for them to sit in until a cable assimilates them. That network is created in case a cable doesn't exist to assimilate it.

As for *when* to create the network, I'm sure if I sat down and stayed up late one night I'd figure it out. It's just a matter of finding which methods would be most appropriate. Maybe in TileEntity.validate(), and the multipart delegation of that?

**Comment by SquidDev** [comment]
The idea of using `.validate()` kinda fills me with dread - I don't really want to hook into things for what they aren't designed for. This is a really tricky problem.

**Comment by SquidDev** [comment]
Apparently deferring peripheral searching until `setWorldObj` doesn't work. We might need to defer it until `updateEntity` instead.

**Comment by SquidDev** [comment]
I've just cloned AE and am going to do some testing to see how they manage it. I obviously don't want to just copy and paste but I'm not clever enough to work this out without some 'inspiration'.

**Comment by ElvishJerricco** [comment]
Apologies for not being able to work on this. I didn't expect to be so busy for so long.

**Comment by SquidDev** [comment]
Don't worry, I've not been busy and have just worked on [other](http://maven.bonzodandd.co.uk/org/squiddev/CCTweaks/1.7.10-0.2-pr1/CCTweaks-1.7.10-0.2-pr1.jar) [stuff](http://www.computercraft.info/forums2/index.php?/topic/21987-mc-1710-cc-165173-cc-tweaks/page__view__findpost__p__220561).

**Comment by SquidDev** [comment]
Man, I so want to add OpenComputer's support with the network - but the interfaces are so different I just don't think it is possible. :frowning:

**Comment by SquidDev** [comment]
Right. After much code reading I think this is the best approach. It involves some magic but seems the best way. When your node is created you call `NetworkHelpers.schedule(INetworkNode)`, this will be in the public API somewhere.

This adds a method to an event queue that calls `NetworkHelpers.joinOrCreateNetwork(INetworkNode)`. When joining a network we then load additional information such as peripherals.

This means nodes don't need to have an update tick but it should work. Thoughts?

**Comment by SquidDev** [comment]
Right, one issue with then handling peripherals on `attachToNetwork` and `detachFromNetwork` is that they are removed when saving NBT. Hrrrmrm.

**Comment by SquidDev** [comment]
Right. I'm a Muppet or I've just been asleep for the last week.

I've only just remembered that you have cables creating networks and joining the other nodes, whilst I'm trying to have every node joins or creates a network when it is created...

I'd prefer the latter as it means we don't have to rely on cable classes but it does then complicate wireless bridges. Ping me when you get online.

**Comment by SquidDev** [comment]
@ElvishJerricco What do you suggest we do?

**Comment by ElvishJerricco** [comment]
I think the schedule method makes sense. But it should probably be in a clas other than NetworkHelpers, since we want it to be public API.

**Comment by SquidDev** [comment]
Yeah, I just put it there for the time being until we start deciding what should be in the public API - probably most of the helpers should be.

**Comment by SquidDev** [comment]
I've done some more work on this on my computer. I can now load a world without crashing! :+1:. However removing a node results in 100% CPU usage (haven't even got round to testing placing a node new node) so there is quite a bit of work for me to do....

**Comment by SquidDev** [comment]
The issue lies in cyclic dependencies with the node scanner:

```
A --- B
 \   /
   C
```

So for instance removing C results in an infinite loop.

**Comment by SquidDev** [comment]
Right, there is still lots to do. (Well, anything prefixed with `TODO`). And of course it needs to be tested.

**Comment by SquidDev** [comment]
More things that probably should be done (not going in main post as they aren't a priority).
 - [ ] Replace set of connections with a more efficient data structure. Ideally we should be able to find connections to/from any node without having to iterate through the list.
 - [ ] Bring back the unit tests. I deleted them in 3bc51af1a10666891fe4d72177e37fa15e373ca0 but it might be worth bringing them back in a different form to ensure that everything works correctly.

**Comment by SquidDev** [comment]
**FIXME:** Client/Server synchronisation is broken with normal modems - but not block ons.

**Comment by SquidDev** [comment]
So I managed to break rendering on cables (see image below) and I don't know how. 

I started work on network bindings, and it is entirely broken - the node shouldn't be removed from the network, connections should be broken instead.

Also written a massively, client side only, network renderer. It renders connections between nodes, and is really, really horrible - but is pretty useful for debugging.

**Comment by SquidDev** [comment]
So, wireless bridges are fixed:

**Comment by SquidDev** [comment]
Multipart is broken. Server side it works fine, client side is really buggy. @ElvishJerricco Does everything look OK so far?

**Comment by ElvishJerricco** [comment]
That network renderer is awesome! And I'm too busy today to look into it, but I imagine the bugs exist because so much is trying to be done on both client and server side. Considering how inefficient and bug prone this is (because several things only happen server side), I think it makes sense to have the client side not do any of these things, and rely on syncing. The only thing that should be necessary to sync is the connection map for rendering. Am I crazy?

**Comment by SquidDev** [comment]
Currently the connection map is recalculated on the client and the server. The issue lies in the fact that neighbour changed events are not fired on the client (for obvious reasons) and so the map is never recalculated. I've tried forcing a sync then redraw but that doesn't seem to work. I'm probably going to read through some code from other mods and see how (and if) they implement caching.

**Comment by SquidDev** [comment]
So a bit of a summary of what I've done:
 - Any 'world interaction' is deferred until the first tick - this involves peripheral and node scanning
 - Remove client side caching of connections - I would love to add this back in, but it really isn't a priority. There should be some performance increases as we cache before each render, and so we don't need to refresh for each icon accessor.

What needs work:
 - Turtle network binding - this is really buggy and needs lots of work.
 - Modem icons - the textures for 'vanilla' modems are really bugged out, this needs fixing.

**Comment by SquidDev** [comment]
@ElvishJerricco I'm going to to a bug hunt and, if you have no objections, am going to merge and post a beta on the forums. I think the other things can be worked on before 0.2 but in another branch seeing as the big bit is done.

**Comment by SquidDev** [comment]
I'm just getting addicted to posting these:

**Comment by ElvishJerricco** [comment]
Haha great. If we're in a good beta stage, posting it is a good plan. Excited to see this finished soon

**Pull request merged**
