### PR TITLE
Config and Patcher

### LINKED ISSUE #41: Only disable crafting of items
[See here](http://www.computercraft.info/forums2/index.php?/topic/23520-communitycraft-cc-173/page__view__findpost__p__220524)

### LINKED ISSUE #42: Config options
Related to #41. Basically - everything needs to be configurable.

### PR DESCRIPTION
**Pull request by SquidDev**
Closes #41 and closes #42.

This rewrites the config and patching systems to use the ConfigGen and Patcher modules. The aim is to implement as many tweaks as possible without  having to reload the game. To quote #3:

> To consider: Use config variables rather than changing the raw ASM as it means MC does not have to be reloaded. How much slower is it?

### CODE REVIEW

**Comment by SquidDev** [comment]
I haven't found any problems with this, so am I OK to merge @ElvishJerricco?

**Comment by Nathan1852** [comment]
Quick suggestion for the config: Could you make an option for all the pushRemote and pullRemote commands? So the bridge works for connecting, but not to push and pull remotely

**Comment by SquidDev** [comment]
[Already done](https://github.com/SquidDev-CC/CC-Tweaks/commit/64c8dcd449d7b20e7986d1da5d7431db4c2689ec#diff-515f77ef75fc52e589b05d2bcbf4d377R187)! The config name isn't great but I'm pretty bad at describing things.

**Comment by Nathan1852** [comment]
Ohh. I just looked at the commit but didn't see it -_-

**Comment by ElvishJerricco** [comment]
Took a quick look, and it seems fine. Go ahead

**Pull request merged**
